### ISSUE TITLE
Citation Request

### ISSUE THREAD

**Issue by benedekrozemberczki** [jjgarau/GNND#1]
Dear @jjgarau,

Your repo uses the PyTorch Geometric Temporal framework. However, you do not cite the paper?

Why?

Bests,

Benedek

**Comment by jjgarau** [comment]
Hi Benedek,

I have updated the README with links to both PyTorch Geometric and PyTorch Geometric Temporal. Sorry for not doing this earlier, and thanks for your contribution.

Best,

Juan

**Comment by benedekrozemberczki** [comment]
Hi there, I am talking about the paper. The repo explicitly asks for citing
the research paper.

**Comment by jjgarau** [comment]
Oh I see, I thought you only meant on Github since the paper is still not published on arXiv yet. I will update the paper with a citation to your work. Don't worry, not citing the repo hasn't been deliberate decision :)

**Comment by ShijieLuo98** [comment]
Can you provide the following data? “data/covid-data/mobility_data.csv”
